AllCops:
  Exclude:
    - .env
    - db/**/**
    - node_modules/**/**
    - bin/**/**
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  Max: 40
Layout/HashAlignment:
  EnforcedColonStyle: table
Layout/CaseIndentation:
  Enabled: false
Layout/LineLength:
  Max: 130
