development:
  adapter: postgresql
  database: working_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: working_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: working_prod
  pool: 5
  timeout: 5000